### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by webdev522** [mp3063/laravel_mail_activation#15]
I'd like to integrate your email verification module into my laravel5.4 project.

But it shows errors such as...

Swift_TransportException in AbstractSmtpTransport.php line 383: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. f9sm15870623pfj.56 - gsmtp
"

I've checked dataabase and found Registration is OK
But I think sending mail has an error.

Kindly check my email configuration.
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=xxx@gmail.com
MAIL_PASSWORD=xxx
MAIL_ENCRYPTION=
MAIL_FROM_ADDRESS=xxx@gmail.com
MAIL_FROM_NAME=Verification

Following configuration is already proved by another project.
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=xxx@gmail.com
MAIL_PASSWORD=xxx
MAIL_ENCRYPTION=

I want your help.

Best Regards.

**Comment by mp3063** [comment]
I'm sorry... Did you manage to solve this problem? This error usualy occurs when you don't fill out FROM_ADDRESS and name_from in config/app.php but I see you fill this info in .env file. Only thing to do is to restart server...

**Comment by webdev522** [comment]
I have just solved my problem depending on your readmd.md.


I missed email configuration.

Thanks

Best Regards.
